/**:
  ros__parameters:
    nb_colors: 10
    visualization_update_period_ms: 5000
    enable_keypoints_visualization: false
    enable_pointclouds_visualization: true
    voxel_size: 0.1
    pose_graph_markers_size: 1.0
    produce_mesh: false
    
    # Storage parameters:
    # map_path is concatened with pose_graph_file_name to create this file 
    # TODO: should I find a way to do this with a relative path?
    map_path: /home/romantwice/Projects/MISTLab/Swarm-SLAM/src/cslam_visualization/unreachable_robot_map
    pose_graph_file_name: pose_graph.json
    enable_map_reading: true
    enable_map_storage: false